name: 24/7 Discord Bot

on:
  push:
    branches: [ main ]
  schedule:
    # Τρέχει κάθε 5 λεπτά! (Το GitHub μπορεί να το καθυστερήσει λίγο, αλλά είναι το πιο συχνό που επιτρέπεται)
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    # Αυτό σταματάει αμέσως το προηγούμενο bot αν ξεκινήσει νέο, αποφεύγοντας τα διπλότυπα
    concurrency:
      group: discord-bot
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install -r requirements.txt
          pip install requests

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # Προσθήκη timeout ώστε αν "κολλήσει" το GitHub, να τερματίζει μόνο του και να ξαναρχίζει το επόμενο
        run: timeout 175m python bot.py || true
