name: 24/7 Discord Bot

on:
  push:
    branches: [ main ]
  schedule:
    # Τρέχει κάθε 5 λεπτά! (Το GitHub μπορεί να το καθυστερήσει λίγο, αλλά είναι το πιο συχνό που επιτρέπεται)
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    # ΣΒΗΣΑΜΕ ΤΟ CONCURRENCY ΑΠΟ ΕΔΩ
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install -r requirements.txt
          pip install requests

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # Βάζουμε μικρότερο timeout (π.χ. 55 λεπτά) για να ανανεώνεται πιο συχνά και καθαρά
        run: timeout 55m python bot.py
